### ISSUE TITLE
Rodar projeto dentro do docker-compose

### ISSUE THREAD

**Issue by filhodanuvem** [filhodanuvem/ytgoapi#4]
:warning: Não é preciso avisar que vai trabalhar numa issue, apenas mande a pull request :wink:. 

Hoje a api em so roda fora do docker-compose, entao mover pra dentro respeitando o health check do banco é uma boa.

**Comment by juliocesar014** [comment]
https://github.com/filhodanuvem/ytgoapi/pull/7
